name: Run Input_Data.py

on:
  schedule:
    # Run every 1 hour instead of 15 mins
    - cron: '0 * * * *'
  workflow_dispatch:

concurrency:
  group: input-data-job
  cancel-in-progress: false

jobs:
  run-dump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Input_Data.py
        env:
          PRABHAT_SECRET_KEY: ${{ secrets.PRABHAT_SECRET_KEY }}
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          USERNAME: ${{ secrets.USERNAME }}
          METABASE_URL: ${{ secrets.METABASE_URL }}
          DAILY_INPUT_QUERY: ${{ secrets.DAILY_INPUT_QUERY }}
          SHEET_ACCESS_KEY: ${{ secrets.SHEET_ACCESS_KEY }}

        run: |
          echo "Workflow triggered at: $(date -u)"
          echo "ðŸš€ Running Input_Data.py..."
          python Input_Data.py
